In [40]:
import scipy
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

## Решить (задание 6.1)

In [41]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
X = np.linalg.solve(A,B)
print(X)

[-9.2         0.9         6.46666667]


## Найти псевдорешение (задание 6.2)



In [42]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
B = np.array([1,7,12,7,15])
x, residual, rank, a = np.linalg.lstsq(A,B, rcond=None)
print(x)

[ 1.13919353 -0.90498444 -0.9009803 ]


## Сколько решений имеет линейная система (задание 6.3)

In [43]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,1,1]])
print(np.linalg.det(A)) 
C = np.concatenate((A,B.T), axis=1)
print(np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001))
# Определитель = 0 и ранг исходной матрицы меньше ранга расширенной - решений не имеет
B1 = np.array([[1,1,1]])
C1 = np.concatenate((A,B1.T), axis=1)
print(np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C1, 0.0001))
# ранг исходной и расширенной матрицы равны, ранг матрицы меньше числа неизвестных - имеет множество решений

0.0
2 3
2 2


## LU-разложение (задание 6.4)

In [44]:
A = np.array([[1,2,3],[2,16,21],[4,28,73]])
B = np.array([1,2,3])
det_A = np.linalg.det(A)

P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
print('det A: ', det_A)
print('Решение: ', np.linalg.solve(A,B))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
det A:  432.00000000000017
Решение:  [ 1.01388889  0.03472222 -0.02777778]


## Найти нормальное псевдорешение (задание  6.5)

In [45]:
def Q(x, y, z):
    return (x**2 + y**2 + z**2)

In [46]:
A = np.array([[1, 2, -1], [8,-5,2]])
B = np.array([1,12])
x, residual, rank, a = np.linalg.lstsq(A, B, rcond=None)
print(x)

[ 1.38191882 -0.18081181  0.0202952 ]


## Найдите одно из псевдорешений вырожденной системы (задание 6.6)

In [48]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([2,5,11])

Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.58790979e-16]]


In [55]:
R1 = R[:2, :2]
B1 = np.dot(np.transpose(Q), B)[:2]
X1 = np.linalg.solve(R1, B1)
X = np.append(X1, 0)
result = np.linalg.norm(X)
print('Одно из псевдорешений: ', result)

Одно из псевдорешений:  1.499999999999996
